language: java
cache:
  directories:
    - $HOME/.gradle
notifications:
  email: false
jdk:
  - oraclejdk8
install: ./gradlew setupCIWorkspace -S
script: ./gradlew clean build -S
before_install:
- chmod a+x gradlew